#!/bin/sh
# MIT License — Copyright (c) 2026 headless-spotify Contributors (see LICENSE).
#
# smoke-test.sh — pre-release gate. Safe by default (no Spotify changes);
# pass --live to also exercise real media controls (restores state after).
#
# Usage: ./scripts/smoke-test.sh [--live]
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SCRIPT_DIR"
LIVE=0
[ "${1:-}" = "--live" ] && LIVE=1

pass=0; fail=0
check() { # check <name> <command...>
  name="$1"; shift
  if "$@" >/dev/null 2>&1; then echo "ok: $name"; pass=$((pass + 1)); else echo "FAIL: $name"; fail=$((fail + 1)); fi
}

echo "== build + unit tests =="
swift build 2>&1 | tail -1
swift test 2>&1 | tail -1

echo "== static checks =="
sh -n install.sh && echo "ok: install.sh syntax"
sh -n uninstall.sh && echo "ok: uninstall.sh syntax"
sh -n scripts/package-release.sh && echo "ok: package-release.sh syntax"
sh -n scripts/build-menubar.sh && echo "ok: build-menubar.sh syntax"
sh -n scripts/smoke-test.sh && echo "ok: smoke-test.sh syntax"
command -v shellcheck >/dev/null && shellcheck -S error install.sh uninstall.sh scripts/*.sh && echo "ok: shellcheck" || echo "skip: shellcheck not installed"
(ruby -ryaml -e 'Dir.glob(".github/workflows/*.yml") { |f| YAML.load_file(f) }' && echo "ok: workflows YAML") 2>/dev/null || echo "skip: ruby/yaml unavailable"
/usr/bin/plutil -lint launchagent/com.headless-spotify.watcher.plist
# The installed agent is generated by the CLI (argv[0] differs by design),
# so compare semantically: same label, KeepAlive, and WatchPaths.
BINPATH="$(pwd)/.build/debug/headless-spotify"
"$BINPATH" watch --print-agent-plist --spotify-app /Applications/Spotify.app --interval 15 | grep -q "com.headless-spotify.watcher" && echo "ok: agent plist generates"

echo "== CLI self-checks (hermetic) =="
check "version" ./.build/debug/headless-spotify --version
check "help" ./.build/debug/headless-spotify --help
check "control dry-run" ./.build/debug/headless-spotify control play --dry-run
! ./.build/debug/headless-spotify hide --spotify-app /nonexistent/Spotify.app >/dev/null 2>&1 && echo "ok: missing app exits nonzero"

echo "== menu bar extra (bundle + menu) =="
BAR_SPEC="$(./.build/debug/headless-spotify-bar --print-menu-spec)"
echo "$BAR_SPEC" | grep -q "headless-spotify" && echo "ok: menu names the project"
echo "$BAR_SPEC" | grep -q "Quit headless-spotify" && echo "ok: menu offers Quit"
! ./.build/debug/headless-spotify-bar --bogus >/dev/null 2>&1 && echo "ok: bar rejects unknown flags"
MENUBAR_OUT="/tmp/smoke-menubar-$$"
CONFIG=debug OUT_DIR="$MENUBAR_OUT" ./scripts/build-menubar.sh >/dev/null
MENUBAR_APP="$MENUBAR_OUT/headless-spotify.app"
/usr/bin/plutil -lint "$MENUBAR_APP/Contents/Info.plist" >/dev/null && echo "ok: menubar Info.plist"
[ "$(/usr/libexec/PlistBuddy -c 'Print :LSUIElement' "$MENUBAR_APP/Contents/Info.plist")" = "true" ] \
  && echo "ok: menubar is LSUIElement (no Dock icon)"
[ -x "$MENUBAR_APP/Contents/MacOS/headless-spotify-bar" ] && echo "ok: menubar executable present"
rm -rf "$MENUBAR_OUT"

echo "== fixture hide/restore cycle =="
FIXTURE="/tmp/smoke-fixture-$$"
mkdir -p "$FIXTURE/Spotify.app/Contents"
/usr/bin/plutil -create xml1 "$FIXTURE/Spotify.app/Contents/Info.plist"
/usr/bin/plutil -replace CFBundleIdentifier -string com.spotify.client "$FIXTURE/Spotify.app/Contents/Info.plist"
check "fixture hide --skip-relaunch" ./.build/debug/headless-spotify hide --skip-relaunch --spotify-app "$FIXTURE/Spotify.app"
check "fixture restore --skip-relaunch" ./.build/debug/headless-spotify restore --skip-relaunch --spotify-app "$FIXTURE/Spotify.app"
test -z "$(ls "$FIXTURE/Spotify.app/Contents" | grep -i backup || true)" && echo "ok: no leftover backups" || { echo "FAIL: leftover backups"; fail=$((fail + 1)); }
rm -rf "$FIXTURE"

if [ "$LIVE" = "1" ]; then
  echo "== live controls (state restored after) =="
  BIN=./.build/debug/headless-spotify
  STATE_BEFORE="$(osascript -e 'tell application "Spotify" to get player state')"
  TRACK_BEFORE="$(osascript -e 'tell application "Spotify" to get name of current track')"
  VOL_BEFORE="$($BIN control volume)"
  check "live pause" $BIN control pause
  sleep 1
  test "$(osascript -e 'tell application "Spotify" to get player state')" = "paused" && echo "ok: live paused" || { echo "FAIL: live paused"; fail=$((fail + 1)); }
  check "live play" $BIN control play
  sleep 1
  test "$(osascript -e 'tell application "Spotify" to get player state')" = "playing" && echo "ok: live playing" || { echo "FAIL: live playing"; fail=$((fail + 1)); }
  check "live next" $BIN control next
  sleep 1
  check "live previous" $BIN control previous
  sleep 1
  TRACK_AFTER="$(osascript -e 'tell application "Spotify" to get name of current track')"
  test "$TRACK_BEFORE" = "$TRACK_AFTER" && echo "ok: track restored ($TRACK_AFTER)" || { echo "FAIL: track changed ($TRACK_BEFORE -> $TRACK_AFTER)"; fail=$((fail + 1)); }
  check "live volume read" $BIN control volume
  # Restore pre-test state.
  if [ "$STATE_BEFORE" = "paused" ]; then $BIN control pause >/dev/null; else $BIN control play >/dev/null; fi
  echo "ok: player state restored ($STATE_BEFORE), volume was $VOL_BEFORE"
  $BIN status --json
else
  echo "== live controls skipped (pass --live to run) =="
fi

echo "== result: $pass passed, $fail failed =="
test "$fail" -eq 0
